---
# tasks file for QuayRegistry

- name: check if image exist
  uri:
    url: "https://quay.io/api/v1/repository/{{ namespace }}/{{ repository }}/{{ image }}"
    method: GET
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    status_code:
      - 200
      - 404
  register: repostate

- name: create-repo
  uri:
    url: https://quay.io/api/v1/repository
    method: POST
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    body:
      repo_kind: "{{ image }}"
      namespace: "{{ namespace }}"
      visibility: "{{ visibility }}"
      repository: "{{ repository }}"
      description: blablabla
    status_code:
      - 201
  when:
    - repostate.status == 404
    - state == "present"


- name: delete-repo
  uri:
    url: "https://quay.io/api/v1/repository/{{ namespace }}/{{ repository }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    status_code:
      - 204
  when:
          #    - repostate.status == 200
    - state == "absent"

