# permissions for end users to edit quayregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayregistry-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - quayregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - quayregistries/status
  verbs:
  - get
