# permissions for end users to view quayregistry--generate-roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayregistry--generate-role-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - quayregistry--generate-roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - quayregistry--generate-roles/status
  verbs:
  - get
