---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for cache.example.com/v1alpha1, Kind: QuayRegistry--generate-role
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - quayregistry--generate-roles
      - quayregistry--generate-roles/status
      - quayregistry--generate-roles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for cache.example.com/v1alpha1, Kind: QuayRegistry
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - quayregistries
      - quayregistries/status
      - quayregistries/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
