# permissions for end users to edit quay-operator-customs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quay-operator-custom-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - quay-operator-customs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - quay-operator-customs/status
  verbs:
  - get
