---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quayregistry--generate-roles.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: QuayRegistry--generate-role
    listKind: QuayRegistry--generate-roleList
    plural: quayregistry--generate-roles
    singular: quayregistry--generate-role
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: QuayRegistry--generate-role is the Schema for the quayregistry--generate-roles API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of QuayRegistry--generate-role
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of QuayRegistry--generate-role
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
